// <auto-generated />
using System;
using Khata.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Khata.Data.Persistence.Migrations
{
    [DbContext(typeof(KhataContext))]
    [Migration("20190208094946_AddedSavedSaleTable")]
    partial class AddedSavedSaleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Khata.Domain.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance");

                    b.Property<int?>("MetadataId");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("CashRegister");
                });

            modelBuilder.Entity("Khata.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.Property<decimal>("Debt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName");

                    b.Property<int?>("MetadataId");

                    b.Property<string>("Note");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Khata.Domain.DebtPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("CustomerId");

                    b.Property<decimal>("DebtBefore");

                    b.Property<string>("Description");

                    b.Property<int>("InvoiceId");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("MetadataId");

                    b.ToTable("DebtPayments");
                });

            modelBuilder.Entity("Khata.Domain.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<int?>("MetadataId");

                    b.Property<int?>("RowId");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("Khata.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<decimal>("Balance");

                    b.Property<string>("Designation");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName");

                    b.Property<int?>("MetadataId");

                    b.Property<string>("NIdNumber");

                    b.Property<string>("Note");

                    b.Property<string>("Phone");

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Khata.Domain.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Khata.Domain.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<decimal>("PaymentDiscountCash");

                    b.Property<decimal>("PaymentPaid");

                    b.Property<decimal>("PaymentSubtotal");

                    b.Property<decimal>("PreviousDue");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Invoice");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Invoice");
                });

            modelBuilder.Entity("Khata.Domain.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Creator")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("admin");

                    b.Property<DateTimeOffset>("ModificationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Modifier")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("admin");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Khata.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<string>("Name");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Khata.Domain.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<DateTimeOffset>("PurchaseDate");

                    b.Property<int>("SupplierId");

                    b.Property<int>("VoucharId");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("VoucharId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Khata.Domain.PurchaseLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("ProductId");

                    b.Property<int?>("PurchaseId");

                    b.Property<int?>("PurchaseReturnId");

                    b.Property<decimal>("Quantity");

                    b.Property<decimal>("UnitPurchasePrice");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("PurchaseReturnId");

                    b.ToTable("PurchaseLineItem");
                });

            modelBuilder.Entity("Khata.Domain.PurchaseReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashBack");

                    b.Property<decimal>("DebtRollback");

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<int>("PurchaseId");

                    b.Property<int>("SupplierId");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseReturns");
                });

            modelBuilder.Entity("Khata.Domain.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashBack");

                    b.Property<int>("CustomerId");

                    b.Property<decimal>("DebtRollback");

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<int>("SaleId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MetadataId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Khata.Domain.SalaryIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("BalanceBefore");

                    b.Property<string>("Description");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MetadataId");

                    b.ToTable("SalaryIssues");
                });

            modelBuilder.Entity("Khata.Domain.SalaryPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("BalanceBefore");

                    b.Property<string>("Description");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MetadataId");

                    b.ToTable("SalaryPayments");
                });

            modelBuilder.Entity("Khata.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<string>("Description");

                    b.Property<int>("InvoiceId");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<DateTimeOffset>("SaleDate");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("MetadataId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Khata.Domain.SaleLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Quantity");

                    b.Property<int?>("RefundId");

                    b.Property<int?>("SaleId");

                    b.Property<int>("Type");

                    b.Property<decimal>("UnitPrice");

                    b.Property<decimal>("UnitPurchasePrice");

                    b.HasKey("Id");

                    b.HasIndex("RefundId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLineItem");
                });

            modelBuilder.Entity("Khata.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Khata.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName");

                    b.Property<int?>("MetadataId");

                    b.Property<string>("Note");

                    b.Property<decimal>("Payable");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Khata.Domain.SupplierPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<int?>("MetadataId");

                    b.Property<decimal>("PayableBefore");

                    b.Property<int>("SupplierId");

                    b.Property<int>("VoucharId");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("VoucharId")
                        .IsUnique();

                    b.ToTable("SupplierPayments");
                });

            modelBuilder.Entity("Khata.Domain.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<int?>("MetadataId");

                    b.Property<int?>("RowId");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Khata.Domain.CustomerInvoice", b =>
                {
                    b.HasBaseType("Khata.Domain.Invoice");

                    b.Property<int>("CustomerId");

                    b.Property<int?>("DebtPaymentId");

                    b.Property<int?>("SaleId");

                    b.Property<int?>("Type");

                    b.HasIndex("CustomerId");

                    b.HasDiscriminator().HasValue("CustomerInvoice");
                });

            modelBuilder.Entity("Khata.Domain.Vouchar", b =>
                {
                    b.HasBaseType("Khata.Domain.Invoice");

                    b.Property<int?>("PurchaseId");

                    b.Property<int>("SupplierId");

                    b.Property<int?>("SupplierPaymentId");

                    b.HasIndex("SupplierId");

                    b.HasDiscriminator().HasValue("Vouchar");
                });

            modelBuilder.Entity("Khata.Domain.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<byte[]>("Avatar");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Role");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Khata.Domain.CashRegister", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Customer", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.DebtPayment", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany("DebtPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.CustomerInvoice", "Invoice")
                        .WithOne("DebtPayment")
                        .HasForeignKey("Khata.Domain.DebtPayment", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Deposit", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Employee", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Expense", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Invoice", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.OwnsMany("Khata.Domain.InvoiceLineItem", "Cart", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("InvoiceId");

                            b1.Property<string>("Name");

                            b1.Property<decimal>("NetPrice");

                            b1.Property<decimal>("Quantity");

                            b1.Property<decimal>("UnitPrice");

                            b1.HasKey("Id");

                            b1.HasIndex("InvoiceId");

                            b1.ToTable("InvoiceLineItem");

                            b1.HasOne("Khata.Domain.Invoice")
                                .WithMany("Cart")
                                .HasForeignKey("InvoiceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Product", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.OwnsOne("Khata.Domain.Inventory", "Inventory", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("AlertAt");

                            b1.Property<decimal>("Stock");

                            b1.Property<decimal>("Warehouse");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.HasOne("Khata.Domain.Product")
                                .WithOne("Inventory")
                                .HasForeignKey("Khata.Domain.Inventory", "ProductId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Khata.Domain.Pricing", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("Bulk");

                            b1.Property<decimal>("Margin");

                            b1.Property<decimal>("Purchase");

                            b1.Property<decimal>("Retail");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.HasOne("Khata.Domain.Product")
                                .WithOne("Price")
                                .HasForeignKey("Khata.Domain.Pricing", "ProductId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Purchase", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Vouchar", "Vouchar")
                        .WithOne("Purchase")
                        .HasForeignKey("Khata.Domain.Purchase", "VoucharId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Khata.Domain.PaymentInfo", "Payment", b1 =>
                        {
                            b1.Property<int>("PurchaseId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("DiscountCash");

                            b1.Property<decimal>("Paid");

                            b1.Property<decimal>("SubTotal");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.HasOne("Khata.Domain.Purchase")
                                .WithOne("Payment")
                                .HasForeignKey("Khata.Domain.PaymentInfo", "PurchaseId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.PurchaseLineItem", b =>
                {
                    b.HasOne("Khata.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Purchase")
                        .WithMany("Cart")
                        .HasForeignKey("PurchaseId");

                    b.HasOne("Khata.Domain.PurchaseReturn")
                        .WithMany("Cart")
                        .HasForeignKey("PurchaseReturnId");
                });

            modelBuilder.Entity("Khata.Domain.PurchaseReturn", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.HasOne("Khata.Domain.Purchase", "Purchase")
                        .WithOne()
                        .HasForeignKey("Khata.Domain.PurchaseReturn", "PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Khata.Domain.Refund", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.HasOne("Khata.Domain.Sale", "Sale")
                        .WithOne()
                        .HasForeignKey("Khata.Domain.Refund", "SaleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Khata.Domain.SalaryIssue", b =>
                {
                    b.HasOne("Khata.Domain.Employee", "Employee")
                        .WithMany("SalaryIssues")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.SalaryPayment", b =>
                {
                    b.HasOne("Khata.Domain.Employee", "Employee")
                        .WithMany("SalaryPayments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Sale", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.CustomerInvoice", "Invoice")
                        .WithOne("Sale")
                        .HasForeignKey("Khata.Domain.Sale", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.OwnsOne("Khata.Domain.PaymentInfo", "Payment", b1 =>
                        {
                            b1.Property<int>("SaleId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("DiscountCash");

                            b1.Property<decimal>("Paid");

                            b1.Property<decimal>("SubTotal");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sale");

                            b1.HasOne("Khata.Domain.Sale")
                                .WithOne("Payment")
                                .HasForeignKey("Khata.Domain.PaymentInfo", "SaleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.SaleLineItem", b =>
                {
                    b.HasOne("Khata.Domain.Refund")
                        .WithMany("Cart")
                        .HasForeignKey("RefundId");

                    b.HasOne("Khata.Domain.Sale")
                        .WithMany("Cart")
                        .HasForeignKey("SaleId");
                });

            modelBuilder.Entity("Khata.Domain.Service", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.Supplier", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Khata.Domain.SupplierPayment", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany("Payments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Vouchar", "Vouchar")
                        .WithOne("SupplierPayment")
                        .HasForeignKey("Khata.Domain.SupplierPayment", "VoucharId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Khata.Domain.Withdrawal", b =>
                {
                    b.HasOne("Khata.Domain.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Khata.Domain.CustomerInvoice", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Khata.Domain.Vouchar", b =>
                {
                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
