// <auto-generated />
using System;
using Khata.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Khata.Data.Persistence.Migrations
{
    [DbContext(typeof(KhataContext))]
    [Migration("20190129070057_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Khata.Domain.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Balance");

                    b.HasKey("Id");

                    b.ToTable("CashRegister");
                });

            modelBuilder.Entity("Khata.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.Property<decimal>("Debt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName");

                    b.Property<string>("Note");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Khata.Domain.DebtPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<int>("CustomerId");

                    b.Property<decimal>("DebtBefore");

                    b.Property<string>("Description");

                    b.Property<int>("InvoiceId");

                    b.Property<bool>("IsRemoved");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("DebtPayments");
                });

            modelBuilder.Entity("Khata.Domain.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<int?>("RowId");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("Khata.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<decimal>("Balance");

                    b.Property<string>("Designation");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName");

                    b.Property<string>("NIdNumber");

                    b.Property<string>("Note");

                    b.Property<string>("Phone");

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Khata.Domain.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Khata.Domain.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsRemoved");

                    b.Property<decimal>("PaymentPaid");

                    b.Property<decimal>("PaymentSubtotal");

                    b.Property<decimal>("PreviousDue");

                    b.HasKey("Id");

                    b.ToTable("Invoice");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Invoice");
                });

            modelBuilder.Entity("Khata.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("Name");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Khata.Domain.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<DateTimeOffset>("PurchaseDate");

                    b.Property<int>("SupplierId");

                    b.Property<int>("VoucharId");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("VoucharId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Khata.Domain.PurchaseLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("ProductId");

                    b.Property<int?>("PurchaseId");

                    b.Property<decimal>("Quantity");

                    b.Property<decimal>("UnitPurchasePrice");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseLineItem");
                });

            modelBuilder.Entity("Khata.Domain.SalaryIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("BalanceBefore");

                    b.Property<string>("Description");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsRemoved");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryIssues");
                });

            modelBuilder.Entity("Khata.Domain.SalaryPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("BalanceBefore");

                    b.Property<string>("Description");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsRemoved");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryPayments");
                });

            modelBuilder.Entity("Khata.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.Property<string>("Description");

                    b.Property<int>("InvoiceId");

                    b.Property<bool>("IsRemoved");

                    b.Property<DateTimeOffset>("SaleDate");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Khata.Domain.SaleLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Quantity");

                    b.Property<int?>("SaleId");

                    b.Property<int>("Type");

                    b.Property<decimal>("UnitPrice");

                    b.Property<decimal>("UnitPurchasePrice");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLineItem");
                });

            modelBuilder.Entity("Khata.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Khata.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("LastName");

                    b.Property<string>("Note");

                    b.Property<decimal>("Payable");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Khata.Domain.SupplierPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<bool>("IsRemoved");

                    b.Property<decimal>("PayableBefore");

                    b.Property<int>("SupplierId");

                    b.Property<int>("VoucharId");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("VoucharId")
                        .IsUnique();

                    b.ToTable("SupplierPayments");
                });

            modelBuilder.Entity("Khata.Domain.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<int?>("RowId");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Khata.Domain.CustomerInvoice", b =>
                {
                    b.HasBaseType("Khata.Domain.Invoice");

                    b.Property<int>("CustomerId");

                    b.Property<int?>("DebtPaymentId");

                    b.Property<decimal>("PaymentDiscountCash");

                    b.Property<int?>("SaleId");

                    b.Property<int?>("Type");

                    b.HasIndex("CustomerId");

                    b.HasDiscriminator().HasValue("CustomerInvoice");
                });

            modelBuilder.Entity("Khata.Domain.Vouchar", b =>
                {
                    b.HasBaseType("Khata.Domain.Invoice");

                    b.Property<int?>("PurchaseId");

                    b.Property<int>("SupplierId");

                    b.Property<int?>("SupplierPaymentId");

                    b.HasIndex("SupplierId");

                    b.HasDiscriminator().HasValue("Vouchar");
                });

            modelBuilder.Entity("Khata.Domain.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<byte[]>("Avatar");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Role");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Khata.Domain.CashRegister", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("CashRegister");

                            b1.HasOne("Khata.Domain.CashRegister")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Customer", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Customers");

                            b1.HasOne("Khata.Domain.Customer")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.DebtPayment", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany("DebtPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.CustomerInvoice", "Invoice")
                        .WithOne("DebtPayment")
                        .HasForeignKey("Khata.Domain.DebtPayment", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("DebtPayments");

                            b1.HasOne("Khata.Domain.DebtPayment")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Deposit", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Deposits");

                            b1.HasOne("Khata.Domain.Deposit")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Employee", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Employees");

                            b1.HasOne("Khata.Domain.Employee")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Expense", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Expenses");

                            b1.HasOne("Khata.Domain.Expense")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Invoice", b =>
                {
                    b.OwnsMany("Khata.Domain.InvoiceLineItem", "Cart", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("InvoiceId");

                            b1.Property<string>("Name");

                            b1.Property<decimal>("NetPrice");

                            b1.Property<decimal>("Quantity");

                            b1.Property<decimal>("UnitPrice");

                            b1.HasKey("Id");

                            b1.HasIndex("InvoiceId");

                            b1.ToTable("InvoiceLineItem");

                            b1.HasOne("Khata.Domain.Invoice")
                                .WithMany("Cart")
                                .HasForeignKey("InvoiceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Invoice");

                            b1.HasOne("Khata.Domain.Invoice")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Product", b =>
                {
                    b.OwnsOne("Khata.Domain.Inventory", "Inventory", b1 =>
                        {
                            b1.Property<int>("ProductId");

                            b1.Property<decimal>("AlertAt");

                            b1.Property<decimal>("Stock");

                            b1.Property<decimal>("Warehouse");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.HasOne("Khata.Domain.Product")
                                .WithOne("Inventory")
                                .HasForeignKey("Khata.Domain.Inventory", "ProductId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Khata.Domain.Pricing", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId");

                            b1.Property<decimal>("Bulk");

                            b1.Property<decimal>("Margin");

                            b1.Property<decimal>("Purchase");

                            b1.Property<decimal>("Retail");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.HasOne("Khata.Domain.Product")
                                .WithOne("Price")
                                .HasForeignKey("Khata.Domain.Pricing", "ProductId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Products");

                            b1.HasOne("Khata.Domain.Product")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Purchase", b =>
                {
                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Vouchar", "Vouchar")
                        .WithOne("Purchase")
                        .HasForeignKey("Khata.Domain.Purchase", "VoucharId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Purchases");

                            b1.HasOne("Khata.Domain.Purchase")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Khata.Domain.PaymentInfo", "Payment", b1 =>
                        {
                            b1.Property<int>("PurchaseId");

                            b1.Property<decimal>("DiscountCash");

                            b1.Property<decimal>("Paid");

                            b1.Property<decimal>("SubTotal");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.HasOne("Khata.Domain.Purchase")
                                .WithOne("Payment")
                                .HasForeignKey("Khata.Domain.PaymentInfo", "PurchaseId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.PurchaseLineItem", b =>
                {
                    b.HasOne("Khata.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Purchase")
                        .WithMany("Cart")
                        .HasForeignKey("PurchaseId");
                });

            modelBuilder.Entity("Khata.Domain.SalaryIssue", b =>
                {
                    b.HasOne("Khata.Domain.Employee", "Employee")
                        .WithMany("SalaryIssues")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("SalaryIssues");

                            b1.HasOne("Khata.Domain.SalaryIssue")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.SalaryPayment", b =>
                {
                    b.HasOne("Khata.Domain.Employee", "Employee")
                        .WithMany("SalaryPayments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("SalaryPayments");

                            b1.HasOne("Khata.Domain.SalaryPayment")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Sale", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.CustomerInvoice", "Invoice")
                        .WithOne("Sale")
                        .HasForeignKey("Khata.Domain.Sale", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Sales");

                            b1.HasOne("Khata.Domain.Sale")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Khata.Domain.PaymentInfo", "Payment", b1 =>
                        {
                            b1.Property<int>("SaleId");

                            b1.Property<decimal>("DiscountCash");

                            b1.Property<decimal>("Paid");

                            b1.Property<decimal>("SubTotal");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.HasOne("Khata.Domain.Sale")
                                .WithOne("Payment")
                                .HasForeignKey("Khata.Domain.PaymentInfo", "SaleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.SaleLineItem", b =>
                {
                    b.HasOne("Khata.Domain.Sale")
                        .WithMany("Cart")
                        .HasForeignKey("SaleId");
                });

            modelBuilder.Entity("Khata.Domain.Service", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Services");

                            b1.HasOne("Khata.Domain.Service")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Supplier", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Suppliers");

                            b1.HasOne("Khata.Domain.Supplier")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.SupplierPayment", b =>
                {
                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany("Payments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Khata.Domain.Vouchar", "Vouchar")
                        .WithOne("SupplierPayment")
                        .HasForeignKey("Khata.Domain.SupplierPayment", "VoucharId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("SupplierPayments");

                            b1.HasOne("Khata.Domain.SupplierPayment")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Khata.Domain.Withdrawal", b =>
                {
                    b.OwnsOne("Khata.Domain.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("Id");

                            b1.Property<DateTimeOffset>("CreationTime");

                            b1.Property<string>("Creator");

                            b1.Property<DateTimeOffset>("ModificationTime");

                            b1.Property<string>("Modifier");

                            b1.HasKey("Id");

                            b1.ToTable("Withdrawals");

                            b1.HasOne("Khata.Domain.Withdrawal")
                                .WithOne("Metadata")
                                .HasForeignKey("Khata.Domain.Metadata", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Khata.Domain.CustomerInvoice", b =>
                {
                    b.HasOne("Khata.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Khata.Domain.Vouchar", b =>
                {
                    b.HasOne("Khata.Domain.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
